apiVersion: v2
name: sd-e-branch-operation
description: "BIAN Service Domain: E-Branch Operation (Operate pattern, Sales and Service)"
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - bian
  - operate
annotations:
  bian/business-area: "Sales and Service"
  bian/business-domain: "Channels"
  bian/asset-type: "Digital Branch Session"
  bian/control-record: "Digital Branch Session Operating Session"
